# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

target "CRUDRecord_Example" do
	pod 'CRUDRecord', :path => '../'
    pod 'ObjectMapper', :path => '~/Documents/xcode/ObjectMapper'
    pod 'ApplicationSupport', :path => '~/Documents/xcode/ApplicationSupport'
end
